spring:
  application:
    name: MiniAutorizador
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  show-actuator: true

security:
  basic:
    username: username
    password: password